### ISSUE TITLE
KinesisFirehoseInput is not allowed for SQL applications under account

### ISSUE THREAD

**Issue by RaphaelEymann** [amanoxsolutions/mlops-realtime-data-ingestion#55]
Currently it is not possible to deploy that stack in a completely clean account:

KinesisFirehoseInput is not allowed for SQL applications under account: 768545273476. Please open a support ticket referencing KinesisFirehoseInput. (Service: AmazonKinesisAnalytics; Status Code: 400; Error Code: UnsupportedOperationException; Request ID: 083a44f3-4062-4b41-b261-074e9783f506; Proxy: null)

https://construct-hub-testing.dev-tools.aws.dev/packages/@aws-solutions-constructs/aws-eventbridge-kinesisstreams/v/2.54.1?lang=typescript
https://construct-hub-testing.dev-tools.aws.dev/packages/@aws-solutions-constructs/aws-kinesisstreams-kinesisfirehose-s3/v/2.54.1?lang=typescript
https://construct-hub-testing.dev-tools.aws.dev/packages/@aws-solutions-constructs/aws-kinesisstreams-lambda/v/2.54.1?lang=typescript
https://construct-hub-testing.dev-tools.aws.dev/packages/@aws-cdk/aws-kinesisanalytics-flink-alpha/v/2.135.0-alpha.0?lang=typescript

**Comment by mlnrt** [comment]
Closes #55
This PR replaces the old Kinesis Analytics architecture with Managed Service for Apache Flink.
